### PR TITLE
fix infinite chatbox

### LINKED ISSUE #3339: [BUG] .nbt set has input cut off
### Describe the bug

Pasting a long string of SNBT with the `.nbt set` command results in the SNBT getting cut off when hitting enter.

Additional notes:
In a previous issue, you stated:
> working as intended, the chat box was successfully extended, but we cannot extend how many characters the server is willing to accept

That makes sense for actual chat messages, but given that the `.nbt` commands are not being sent to the server, why is this issue occurring with them? (I assume the server you referred to is not the internal server).

### Steps to reproduce

```bash
- Enable 'BetterChat'
- Ensure 'Infinite Chat Boxes' is enabled within 'BetterChat'
- Open chat and type .nbt set followed by a string of NBT data that exceeds the normal chat limits
- It should be colored blue in the chat box, to indicate no errors
- Hit enter
- Meteor will give an error because the submission was cut off, despite the whole string being there when typed/pasted
```

### Link to crash report/log if applicable (https://mclo.gs)

_No response_

### Meteor Version

0.5.2 1781

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

### LINKED ISSUE #3346: Make infinite chat from Better Chat Infinite again for meteor commands.
### Describe the bug

You can not:

.nbt set [255 characters of nbt]

it cuts off characters when entering this meteor command. This worked in meteor-client-0.5.1-1592 on 1.19.2 and I wish it would still work the latest version, 1.19.3

### Steps to reproduce

```bash
.nbt set [255 characters of nbt]

[Render thread/INFO]: [CHAT] [Meteor] Expected '}' at position 255: ...g1YjMyYjBk<--[HERE]
```

### Link to crash report/log if applicable (https://mclo.gs)

_No response_

### Meteor Version

meteor-client-0.5.2-1781

### Minecraft Version

1.19.3

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

### PR DESCRIPTION
**Pull request by Wide-Cat**
## Type of change

- [x] Bug fix
- [ ] New feature

## Description

I assume infinite chatbox was broken after 8db58dfe2285cee7618437f1ba9ac3e473e2153d, since before that meteor commands were captured before they were truncated in the sendMessage method, allowing infinite chatbox to work more easily. This resolves the issue.

## Related issues

Closes #3339
Closes #3346 

# How Has This Been Tested?

Local paper server with an extremely long .give command

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have added comments to my code in more complex areas.
- [x] I have tested the code in both development and production environments.

### CODE REVIEW

File: src/main/java/meteordevelopment/meteorclient/mixin/StringHelperMixin.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+import org.spongepowered.asm.mixin.Mixin;
+import org.spongepowered.asm.mixin.injection.At;
+import org.spongepowered.asm.mixin.injection.ModifyArg;
+
+@Mixin(StringHelper.class)
+public class StringHelperMixin {
+
+    @ModifyArg(method = "truncateChat", at = @At(value = "INVOKE", target = "Lnet/minecraft/util/StringHelper;truncate(Ljava/lang/String;IZ)Ljava/lang/String;"), index = 1)
+    private static int injected(int maxLength) { // this method is only used in one place, to truncate chat messages, so it's fine to do this
+        return (Modules.get().get(BetterChat.class).isInfiniteChatBox() ? Integer.MAX_VALUE : 256);
```
Comment (MineGame159) [inline src/main/java/meteordevelopment/meteorclient/mixin/StringHelperMixin.java:20]: If it is not enabled you should return the original argument
