### PR TITLE
resolve #2395, #2396

### LINKED ISSUE #2395: [Bug] Banner preview crash
### Describe the bug

Holding left alt to preview this banner causes a client crash
image
No additional nbt tags, server 1.18.2 with VIA
[crash-2022-06-15_13.39.46-client.txt](https://github.com/MeteorDevelopment/meteor-client/files/8908559/crash-2022-06-15_13.39.46-client.txt)

Funny is that it likely a VIA bug because preview of same item works fine in singleplayer....

### Steps to reproduce

```bash
Preview a banner
```

### Meteor Version

dev 1501

### Minecraft Version

1.19

### Operating System

Linux

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

### LINKED ISSUE #2396: [Suggestion] Make Autotool use swords on bamboo
### Describe the feature

Its just a tiny little thing but swords are the most effective tool to mine/cut bamboo with since swords instantly break bamboo

### Before submitting a suggestion

- [X] This feature doesn't already exist in the client.
(I have checked every module and their settings on the **latest dev build**)

- [X] This wasn't already suggested.
(I have checked every suggestion on github)

- [X] This feature is a valid suggestion.
(I have read the FAQs and Guides)

### PR DESCRIPTION
**Pull request by Wide-Cat**
resolves #2395
resolves #2396

### CODE REVIEW

File: src/main/java/meteordevelopment/meteorclient/systems/modules/render/BetterTooltips.java [hunk 1]
```diff
@@ -80,7 +80,7 @@ public class BetterTooltips extends Module {
     );
 
     public final Setting<Boolean> alwaysShow = sgGeneral.add(new BoolSetting.Builder()
-        .name("always-show")
+        .name("bypass-'hideflag'-nbt")
```
Comment (MineGame159) [inline src/main/java/meteordevelopment/meteorclient/systems/modules/render/BetterTooltips.java:83]: I think the old name is better, a normal user doesn't know what that means and in this case the description won't help either.

Comment (arlomcwalter) [reply src/main/java/meteordevelopment/meteorclient/systems/modules/render/BetterTooltips.java:83]: cap, the name "always show" is so ambiguous
