### PR TITLE
Active checkbox changes on toggle event

### LINKED ISSUE #3223: Module's active check stays when module is toggle
### Describe the bug

If a module is toggled via code (`Modules.get().get(module).toggle()`) while its settings menu is open, it's 'Active' checkmark does not update to match.

### Steps to reproduce

```bash
j
```

### Link to crash report/log if applicable (https://mclo.gs)

_No response_

### Meteor Version

0.5.2-1754

### Minecraft Version

1.19.3

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest dev build).

### PR DESCRIPTION
**Pull request by Soda5601**
fixes #3223

### CODE REVIEW

File: src/main/java/meteordevelopment/meteorclient/gui/screens/ModuleScreen.java [hunk 1]
```diff
@@ -106,6 +108,11 @@ private void onModuleBindChanged(ModuleBindChangedEvent event) {
         keybind.reset();
     }
 
+    @EventHandler
+    private void onActiveModulesChanged(ActiveModulesChangedEvent event) {
+        this.active.checked = Modules.get().getActive().contains(module);
```
Comment (MineGame159) [inline src/main/java/meteordevelopment/meteorclient/gui/screens/ModuleScreen.java:113]: Why didn't you just do `this.active.checked = module.isActive();`?
